name: StudyGroupsManager Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test and Generate Report
      run: dotnet test --verbosity normal --logger html

    - name: Send Test Report Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.mailsac.com
        server_port: 465
        username: ${{ secrets.EMAIL_ADDRESS }}
        password: ${{ secrets.API_KEY }}
        subject: StudyGroupsManager Test Report
        to: ${{ secrets.EMAIL_ADDRESS }}
        from: ${{ secrets.EMAIL_ADDRESS }}
        body: Here is the latest test report of StudyGroupsManager.
        attachments: ./TestResults/TestResult_*.html
